Models/ActionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Chapter2MyApp.Models
{
    public enum Type
    {
        INSECT,
        ANIMAL,
        PLANT,
        VIRUS,
        FUNGI
    }
    public class ActionModel
    {
        public int number { get; set; }
        public string name { get; set; }
        public Type what { get; set; }
    }
}

Models/RequestGameModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Chapter2MyApp.Models
{
    public class RequestGameModel
    {
        [Required(ErrorMessage = "Title Required")]
        [DisplayName("Game Title")]
        public string Title { get; set; }
        
        [Required(ErrorMessage = "Platform Required")]
        [DisplayName("Game Platform")]
        public string Platform { get; set; }
        
        [Required(ErrorMessage = "Release Date")]
        [DisplayName("Release Date")]
        [RegularExpression(@"^\d{1,2}\/\d{1,2}\/\d{4}$", ErrorMessage = "Date format is mm/dd/yyyy.")]
        public string ReleaseDate { get; set; }




    }
}

Controllers/ActionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Chapter2MyApp.Models;

namespace Chapter2MyApp.Controllers
{
    public class ActionController : Controller
    {
        // GET: Action
        public ActionResult Index()
        {
            return View();
        }
        
        // GET: Action
        public ActionResult Layout()
        {
            return View();
        }
        
        public ActionResult Css()
        {
            return View();
        }

        public ActionResult InputPage(int input = 0)
        {
            string[] pages = new string[]{ "Index", "Layout", "Css", "InputPage" };
            input = input >= 0 && input < pages.Length ? input : 0;
            return View(pages[input]);
        }
        public ActionResult RequestGame()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RequestGame(RequestGameModel title)
        {
            try
            {
                return RedirectToAction("Thanks");
            }
            catch (Exception)
            {

                throw;
            }
        }

        public ActionResult Thanks()
        {
            return View();
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chapter2MyApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Action/Css.cshtml
@{
    ViewBag.Title = "Css";
    Layout = null;
}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <head>
        <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
        <link href="~/Content/Action.css" rel="stylesheet">
    </head>
    <title>Css Page</title>
</head>
<body>
    <h2>Css</h2>
</body>
</html>

Views/Action/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Views/Action/InputPage.cshtml
@{
    ViewBag.Title = "InputPage";
}

<h2>InputPage</h2>

Views/Action/Layout.cshtml
@{
    ViewBag.Title = "Layout";
}

<h2>Layout</h2>

Views/Action/RequestGame.cshtml
@model Chapter2MyApp.Models.RequestGameModel

@{
    ViewBag.Title = "RequestGame";
}

    <img src="~/Content/r67xj0lo.bmp" alt="Games" />

<h2>RequestGame</h2>

@using (Html.BeginForm("Thanks", "Action", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()
    @Html.LabelFor(m => m.Title)<br/>
    @Html.EditorFor(m => m.Title) @Html.ValidationMessageFor(m => m.Title)<br />
    <p/>
    @Html.LabelFor(m => m.Platform)<br/>
    @Html.DropDownListFor(m => m.Platform, new List<SelectListItem> {
        new SelectListItem{Text="PS1", Value="PS1"},
        new SelectListItem{Text="PS2", Value="PS2"},
        new SelectListItem{Text="PS3", Value="PS3"},
        new SelectListItem{Text="PS4", Value="PS4"},
        new SelectListItem{Text="NES", Value="NES"},
        new SelectListItem{Text="SNES", Value="SNES"},
        new SelectListItem{Text="XBOX", Value="XBOX"},
        new SelectListItem{Text="GAMEMAN", Value="GAMEMAN"}
    }
    , "Please select") @Html.ValidationMessageFor(m => m.Platform)<br />
    <p/>
    @Html.LabelFor(m => m.ReleaseDate)<br/>
    @Html.EditorFor(m => m.ReleaseDate) @Html.ValidationMessageFor(m => m.ReleaseDate)<br />
    <p/>
    <input type="submit" name="Submit Game" />
}

Views/Action/Thanks.cshtml
@{
    ViewBag.Title = "Thanks";
    string title = "", platform = "", releaseDate = "";

    bool listGames = true;

    string[] gameTitles = new string[] { "Halo Master Chief Collection", "Blazblue", "Super Smash Brother Ultimate", "Risk of Rain 2" };
    string[] gamePlatforms = new string[] { "PC/XBOX ONE", "PS3/XBOX 360", "Nintendo Switch", "PC" };
    string[] gameReleaseDates = new string[] { "November 11, 2014", "November 19, 2008", "December 7, 2018", "March 28, 2019" };

    if (IsPost)
    {
        title = Request.Form["Title"];
        platform = Request.Form["Platform"];
        releaseDate = Request.Form["ReleaseDate"];
    }
}

    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Thanks for your submition.</title>
    </head>
    <body>
        <form action="" method="post">
            <p/>
            <h1>Thanks for submitting your answer!</h1>
            <p/>
            It looks like you've requested the game "@title". <br/>
            On the platform "@platform". <br />
            Which was released "@releaseDate".
            <br/>
            <p><h2>Here are a collection of games I like.</h2></p>
            @{
                if (listGames)
                {
                    for (int i = 0; i < gameTitles.Length; i++)
                    {
                        <h3>@gameTitles[i]</h3>
                        @gamePlatforms[i] <br/>
                        @gameReleaseDates[i] <br/>
                        switch (gameTitles[i]) {
                            case "Blazblue":
                                    <p>This is probably my favorite on the list.</p>
                                break;
                            case "Risk of Rain 2":
                                    <p>I enjoy playing this game with friends..</p>
                                break;
                            case "Halo Master Chief Collection":
                                <p>I've enjoyed these games for years.</p>
                                break;
                            default:
                                <p>Just a fantastic game.</p>
                                break;
                        }
                    }
                }
            }
        </form>
    </body>
    </html>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Chapter 3 Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Layout", "Layout", "Action")</li>
                    <li>@Html.ActionLink("Css", "Css", "Action")</li>
                    <li>@Html.ActionLink("RequestGame", "RequestGame", "Action")</li>
                    <li>@Html.ActionLink("InputPage", "InputPage", "Action")</li>
                    <li>@Html.ActionLink("Thanks", "Thanks", "Action")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>